// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4jzlgm2oTEMca3NwywKeFrEIHQByM1Uk',
    appId: '1:801432222751:android:29024d0d652e0a3a3ce92a',
    messagingSenderId: '801432222751',
    projectId: 'notebook-abc42',
    storageBucket: 'notebook-abc42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0oPehV7dbN-G0Rq3Q8h9CDJzdDWxyrB4',
    appId: '1:801432222751:ios:965f552bc05953753ce92a',
    messagingSenderId: '801432222751',
    projectId: 'notebook-abc42',
    storageBucket: 'notebook-abc42.firebasestorage.app',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0oPehV7dbN-G0Rq3Q8h9CDJzdDWxyrB4',
    appId: '1:801432222751:ios:965f552bc05953753ce92a',
    messagingSenderId: '801432222751',
    projectId: 'notebook-abc42',
    storageBucket: 'notebook-abc42.firebasestorage.app',
    iosBundleId: 'com.example.notebook',
  );
}
